### ISSUE TITLE
`GET /tools` endpoint not respecting `limit` and `offset` parameters

### ISSUE THREAD

**Issue by ltwmori** [elixir-cloud-aai/trs-filer#104]
I am currently working on implementing pagination in the TRS web-component and have been testing the API endpoint deployed at https://trs-filer-test.rahtiapp.fi/ga4gh/trs/v2/ui/#/GA4GH/toolsGet for pagination in the TRS web-component. However, I've noticed that the `offset` and `limit` parameters do not appear to be working as expected. For instance, when I try to set `limit` as 1 on https://trs-filer-test.rahtiapp.fi/ga4gh/trs/v2/tools?limit=1, the endpoint returns all records instead of the expected 1. The same issue occurs with other numbers as well.

I am aware of the previous issue (#23 ) and the subsequent pull request (#98 ) that aimed to resolve this. However, it seems that the issue still persists. Could you please provide an update on the status of this fix and let me know when a version of the backend with a working pagination feature for this endpoint might be _**deployed**_?

Thank you.

**Comment by kushagra189** [comment]
@ltwmori on it. Fixing it ASAP.

**Comment by kushagra189** [comment]
Will be fixed once #105 (code completed, review pending) and #98 (testing pending)  are closed in order.

**Comment by kushagra189** [comment]
This is fixed via #98 . Please check and re-open if not functional. 😀
