### ISSUE TITLE
Update GET /tools/{id}/versions/{version_id} endpoint

### ISSUE THREAD

**Issue by kushagra189** [elixir-cloud-aai/trs-filer#24]
User mongo filters for extracting the specific version. A minor change is required.
Current Flow : Extracting tool object and iterating over the versions to extract the required version.
Required : Use pymongo filter methods to extract the object.

Refer `toolsIdVersionsVersionIdGet` implementation under `server.py`.

**Comment by uniqueg** [comment]
Closed by #38
