### ISSUE TITLE
Add GET endpoints

### ISSUE THREAD

**Issue by kushagra189** [elixir-cloud-aai/trs-filer#4]
Add the following TRS endpoints :
- [x] `GET /tools/{tool_id}`: Get a particular tool
- [x] `GET /tools/{tool_id}/versions`: Get versions of a particular tool
- [x] `GET /tools/{tool_id}/versions/{version_id}`: Get particular tool version
- [x] `GET /tools`: Get all tools
- [x] `GET /tools/{id}/versions/{version_id}/{type}/descriptor`: Get the tool descriptor
- [x] `GET /tools/{id}/versions/{version_id}/{type}/descriptor/{relative_path}`: Get additional tool descriptor files
- [x] `GET /tools/{id}/versions/{version_id}/{type}/tests`: Get a list of test jsons
- [x] `GET /tools/{id}/versions/{version_id}/{type}/files`: Get a list of objects that contain the relative path and file type
- [x] `GET tools/{id}/versions/{version_id}/containerfile`: Get container specs
- [x] `GET /toolClasses`: Get all tool types
- [x] `GET /service-info`: Get service info

Further schema details can be seen [here](https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/openapi/openapi.yaml).

**Comment by uniqueg** [comment]
Last remaining TRS `GET` endpoint implemented by #84
