### ISSUE TITLE
Registering tool without tool class identifier yields Internal Server Error response

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/trs-filer#77]
### Description

`POST`ing or `PUT`ting a tool without specifying a tool class identifier returns a `500/InternalServerError` response because of a `KeyError` in [this line](https://github.com/elixir-cloud-aai/trs-filer/blob/4cd8dd9c2839ec0f4c4e84645daaceafd614184c/trs_filer/ga4gh/trs/endpoints/register_objects.py#L188).

### Proposed solution

If [tool class validation](https://github.com/elixir-cloud-aai/trs-filer/blob/4cd8dd9c2839ec0f4c4e84645daaceafd614184c/trs_filer/config.yaml#L123) is disabled, registering a new tool class on the fly should be possible, even without a tool class identifier, i.e., while a tool class identifier _can_ be provided, a unique random identifier should be generated if absent (compare behavior between `POST /toolClasses` and `PUT /toolClasses`).

**Comment by uniqueg** [comment]
This is tricky as in the current setup the write operation for the tool classes collection occurs _after_ registering the tool. This issue should thus best be fixed once the race conditions are addressed via transactions or schema refactoring (#83).

**Comment by uniqueg** [comment]
This can now be fixed

**Comment by kushagra189** [comment]
Fixing this.
